// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThKPS0A52rSTXRtziKEwDtSbHsGXMY-0',
    appId: '1:436433312631:web:1d25f423a4bc06ccca1f72',
    messagingSenderId: '436433312631',
    projectId: 'chatapp-92b48',
    authDomain: 'chatapp-92b48.firebaseapp.com',
    storageBucket: 'chatapp-92b48.firebasestorage.app',
    measurementId: 'G-6KWM68XZFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl8EKTL30AaQeC8UQzlz3hHlnhkWCGGTA',
    appId: '1:436433312631:android:d065454a8b2bcb89ca1f72',
    messagingSenderId: '436433312631',
    projectId: 'chatapp-92b48',
    storageBucket: 'chatapp-92b48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu0RhMIQZjWnirDUuPDjkPzX2H_jx5f-E',
    appId: '1:436433312631:ios:7524369e33ee3192ca1f72',
    messagingSenderId: '436433312631',
    projectId: 'chatapp-92b48',
    storageBucket: 'chatapp-92b48.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu0RhMIQZjWnirDUuPDjkPzX2H_jx5f-E',
    appId: '1:436433312631:ios:7524369e33ee3192ca1f72',
    messagingSenderId: '436433312631',
    projectId: 'chatapp-92b48',
    storageBucket: 'chatapp-92b48.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAThKPS0A52rSTXRtziKEwDtSbHsGXMY-0',
    appId: '1:436433312631:web:0610a8c6079a776aca1f72',
    messagingSenderId: '436433312631',
    projectId: 'chatapp-92b48',
    authDomain: 'chatapp-92b48.firebaseapp.com',
    storageBucket: 'chatapp-92b48.firebasestorage.app',
    measurementId: 'G-VJPWLV787Q',
  );
}
